name: TransLeish1
dependencies:
  - python=3.8.10
  - pandas=2.0.3
  - openpyxl
  - matplotlib=3.7.1
  - scipy=1.8.1
  - tqdm
  - pip
  - pip:
    - git+https://github.com/Wheeler-Lab/LeishFASTQ@v1.0
